spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mijeong-test-mysql.ct4mmkc0c68e.ap-northeast-2.rds.amazonaws.com:3306/testdb
    username: admin
    password: madp0116
    hikari:
      connection-timeout: 15000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug