spring:
  config:
    activate:
      on-profile: local

  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  # DataSource 설정
  datasource:
    url: jdbc:h2:~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
